version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./storage/postgres:/var/lib/postgresql/data
volumes:
  db:
    driver: local
